### ISSUE TITLE
Stuck in combat result issue

### ISSUE THREAD

**Issue by NickFuchs13** [garfieldbanks/MonsterSanctuaryMods#2]
It's about the "being stuck in the combat results" bug of the mod in Nexus. I tried to disable every mod one by one and all of them. Neither solved the problem. I'm just stuck in the results, no matter the battle:
![image](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/143627894/71548ab9-04a5-4dfa-b4d8-2d8f4e9aa077)

And, after disable all mods, the skills just disappear from the options. It is only the basic options and all attacks are basics:
![image](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/143627894/9362c0ca-f1ed-45aa-9b80-97561202ba3b)

I saw the guy in Nexus with this issue months ago, the only one i found in the internet with the same problem. Tried all the sugested methods but none of them worked.
Did you managed to solve that? I loved your mod but that broke my game with that.
Thanks anyway.

**Comment by garfieldbanks** [comment]
What changes did you make to the default settings?

**Comment by garfieldbanks** [comment]
Also how long did it work for? Which specific actions did you take in-game
just before the issue occurred?

**Comment by garfieldbanks** [comment]
Exit the game and rename the BepInEx/config folder to BepInEx/config-old.
This will reset all mod settings. Then start a new game and when you make
changes to the default game settings make a note of it. Keep track of
exactly what you do and exactly when the bug occurs again (if ever). If you
do this I have a chance of being able to fix the bug for everyone.

**Comment by garfieldbanks** [comment]
If the bug occurs again after following these instructions, upload a zip
archive of your BepInEx/config folder to github and I can see your settings
there.

**Comment by NickFuchs13** [comment]
Same. Did it but the error persists.
[config.zip](https://github.com/garfieldbanks/MonsterSanctuaryMods/files/12479123/config.zip)
Thanks again

**Comment by garfieldbanks** [comment]
Looks like you're missing several .cfg files. Are you sure you didn't
remove any of the DLL files? Do you have all of these?
[image: image.png]

**Comment by garfieldbanks** [comment]
-a---           5/19/2023  3:43 PM           8704
garfieldbanks.MonsterSanctuary.CombatSpeed.dll
-a---           5/19/2023  3:43 PM          11776
garfieldbanks.MonsterSanctuary.DataDumper.dll
-a---           5/19/2023  3:43 PM           8192
garfieldbanks.MonsterSanctuary.DisplayUnhatchedEggs.dll
-a---           5/19/2023  3:43 PM           8192
garfieldbanks.MonsterSanctuary.Fly.dll
-a---           5/19/2023  3:43 PM           7680
garfieldbanks.MonsterSanctuary.FreeJump.dll
-a---           5/19/2023  3:43 PM          13312
garfieldbanks.MonsterSanctuary.GetAllArmyRewards.dll
-a---           5/19/2023  3:43 PM           8192
garfieldbanks.MonsterSanctuary.HatchMaxLevelEggs.dll
-a---           5/19/2023  3:43 PM          12800
garfieldbanks.MonsterSanctuary.LevelCaps.dll
-a---           5/19/2023  5:14 PM          32256
garfieldbanks.MonsterSanctuary.LuckyRandomizer.dll
-a---           5/19/2023  3:43 PM          20992
garfieldbanks.MonsterSanctuary.ModsMenu.dll
-a---           5/20/2023  1:14 PM          47616
garfieldbanks.MonsterSanctuary.MyTweaks.dll
-a---           5/19/2023  3:43 PM           8192
garfieldbanks.MonsterSanctuary.NewGamePlusMonsterAbilities.dll
-a---           5/19/2023  3:43 PM           9216
garfieldbanks.MonsterSanctuary.NewGamePlusMonsterArmy.dll
-a---           5/19/2023  3:43 PM          13824
garfieldbanks.MonsterSanctuary.NGPlusOptions.dll
-a---           5/19/2023  3:43 PM          23040
garfieldbanks.MonsterSanctuary.RandomRandomizer.dll
-a---           5/19/2023  3:43 PM           9728
garfieldbanks.MonsterSanctuary.ShiftColorName.dll
-a---           5/19/2023  3:43 PM          10752
garfieldbanks.MonsterSanctuary.ShowOnlyValidEvolutions.dll
-a---           5/19/2023  3:43 PM           8192
garfieldbanks.MonsterSanctuary.StartButtonConfirm.dll

**Comment by garfieldbanks** [comment]
If you are missing those files and you didn't remove them yourself I wonder
if your antivirus is removing them. Might be good to check if this is the
case.

**Comment by NickFuchs13** [comment]
I have, all of them and my antivirus is disabled.
But now comparing just noted that the config file don't have all the plugins archives

**Comment by NickFuchs13** [comment]
Tried the same process, new config file, and still the problem with the combat result
[config.zip](https://github.com/garfieldbanks/MonsterSanctuaryMods/files/12479557/config.zip)

**Comment by garfieldbanks** [comment]
What is your game version?

**Comment by garfieldbanks** [comment]
Try renaming your Documents/My Games/Monster Sanctuary to Documents/My
Games/Monster Sanctuary-old. Then try a fresh new game.

**Comment by garfieldbanks** [comment]
Are you using BepInEx 5.4.21 or 5.4.22?

**Comment by garfieldbanks** [comment]
If you are using 5.4.22, try 5.4.21 instead just in case.

>

**Comment by NickFuchs13** [comment]
v2.0.0.55
BepInEx_x64_5.4.22.0

**Comment by garfieldbanks** [comment]
If none of this works try renaming your actual Monster Sanctuary game
folder and re-download / re-install it and try all of this again.

>

**Comment by garfieldbanks** [comment]
You have an old version of the game.

>

**Comment by garfieldbanks** [comment]
Try updating to the latest version of the game.

**Comment by garfieldbanks** [comment]
My guess is that is the problem of the other person who reported this as
well.

>

**Comment by NickFuchs13** [comment]
I'll try now

**Comment by garfieldbanks** [comment]
If it works after updating to the latest version of the game you can close
this issue. Thank you for helping figure this out!

**Comment by NickFuchs13** [comment]
Yep, solved. Just the wrong version.
I wasn't even expecting to solution that so soon.
Thank you!
