### ISSUE TITLE
trouble installing mod

### ISSUE THREAD

**Issue by kotakotta** [garfieldbanks/MonsterSanctuaryMods#6]
cannot install the mod.. what is wrong with my file?
![スクリーンショット (407)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/6d762081-bc60-4f18-aa4a-7a45fbb24a9f)
![スクリーンショット (408)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/e3e77f64-d6d5-4adf-ab49-5a4ac0799a84)
![スクリーンショット (409)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/2ac1a857-eacd-4bcc-bcc4-c839845584f3)
![スクリーンショット (410)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/7cd80c61-dc27-4552-b7af-df4bc8f4dbbc)

**Comment by garfieldbanks** [comment]
You need to use BepInEx 5.4.22:
https://github.com/BepInEx/BepInEx/releases/tag/v5.4.22

**Comment by kotakotta** [comment]
I tried already with belpnex 5.4.22, but it didnt work too
![スクリーンショット (411)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/3fa86b2e-a534-4248-b063-5b067390a5a6)
![スクリーンショット (413)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/fede06ec-f7e7-401b-845b-65a4b6a39835)
![スクリーンショット (414)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/0f0428de-c862-43a1-adc1-967e72d3d616)
![スクリーンショット (412)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/9eddc227-2e32-4790-9ff0-fbbe374eac22)

**Comment by garfieldbanks** [comment]
Try the windows x64 release:
https://github.com/BepInEx/BepInEx/releases/download/v5.4.22/BepInEx_x64_5.4.22.0.zip

And rename the folder to just "BepInEx" instead of "BepInEx_x64..."

**Comment by garfieldbanks** [comment]
Actually I think you're making a mistake on the extraction step. Only take
the contents of the zip file and put them directly into the main game
folder. These files exactly as they are here:
[image: image.png]

**Comment by garfieldbanks** [comment]
In case that image doesn't show up:
https://pasteboard.co/XpN2WcM7fiLP.png

**Comment by kotakotta** [comment]
![スクリーンショット (415)](https://github.com/garfieldbanks/MonsterSanctuaryMods/assets/167187654/a7991031-adbf-473f-b163-a3e765ef0f10)
thank you sooo much!!!

**Comment by garfieldbanks** [comment]
You're welcome! Thanks for verifying that the mod works in another language!

If you don't have any more questions, please close this issue.
